apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetherscript-marketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tetherscript-marketing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tetherscript-marketing
    spec:
      imagePullSecrets:
        - name: gcp-artifact-registry
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/spotlessbinco/codetether/tetherscript-marketing-site:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
